### PR TITLE
Fix zero amount input bug and summary formatting bug

### LINKED ISSUE #207: [PE-D][Tester A] Code: summary-income and summary-expense mixes decimals
Both are mixing 1 decimals with 2 decimals. Examples from UG (summary income and summary expense):

-----------------------------------------------
Here is an overall summary of your expenses!
Total Expense: 40.0
Here is a breakdown of your expense:
TRANSPORT: 10.00 (25.00%)
FOOD: 30.00 (75.00%)
Your most spent on category is: FOOD
-----------------------------------------------

and

----------------------------------------------
Here is an overall summary of your income!
Total Income: 30.0
Here is a breakdown of your income:
SALARY: 20.00 (66.67%)
INVESTMENT: 10.00 (33.33%)
Your highest source of income is: SALARY
----------------------------------------------

line 2 for both, vs the other fomattings.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`

### LINKED ISSUE #216: [PE-D][Tester D] add-expense and add-income accept zero-amount entries
The `add-expense` and `add-income` commands currently accept an amount of `0` without any warning or error. While the User Guide specifies that the amount must be "non-negative", which technically includes zero, this behavior is undesirable for a finance tracker.

Zero-amount transactions serve no practical purpose, clutter the user's data lists, and are almost certainly the result of a data entry error. Accepting these "useless" entries pollutes the transaction log and can skew financial summaries if they are not noticed and manually deleted.

Try `add-expense a/0 c/food d/2025-10-31`. Run `list-expense`.

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by goodguyryan**
Fixes #216 
Fixes #207

### CODE REVIEW

File: src/main/java/seedu/fintrack/FinanceManager.java [hunk 1]
```diff
@@ -434,4 +434,19 @@ public Map<IncomeCategory, Double> getIncomeByCategory() {
...
+        if (totalAmount <= 0) {
+            LOGGER.log(Level.INFO, "calculatePercentage returns 0 to prevent NaN error.");
+            return 0.0;
+        }
+
+        double percent = (amount / totalAmount) * 100.0;
+        assert !Double.isNaN(percent) : "Percent should be a number.";
+        LOGGER.log(Level.INFO, "calculatePercentage called successfully.");
+        return percent;
+    }
```
Comment (duckyfuz) [inline src/main/java/seedu/fintrack/FinanceManager.java]: I think it's good that this logic is encapsulated in a function

File: src/main/java/seedu/fintrack/Parser.java [hunk 2]
```diff
@@ -752,9 +752,9 @@ public static Income parseModifyIncomeWithDefaults(String input, Income oldIncom
                     LOGGER.log(Level.WARNING, "Non-finite amount provided: {0}.", amount);
                     throw new IllegalArgumentException("Amount must be finite.");
                 }
-                if (amount < 0) {
-                    LOGGER.log(Level.WARNING, "Negative amount provided: {0}.", amount);
-                    throw new IllegalArgumentException("Amount must be non-negative.");
+                if (amount <= 0) {
+                    LOGGER.log(Level.WARNING, "Negative/Zero amount provided: {0}.", amount);
+                    throw new IllegalArgumentException("Amount must be more than 0.");
```
Comment (duckyfuz) [inline src/main/java/seedu/fintrack/Parser.java]: yes, more than 0 is a better error to show here

**Review by duckyfuz — APPROVED** [review]
