### PR TITLE
Reject non-ASCII CLI input

### LINKED ISSUE #173: Add safeguard to reject non-ASCII CLI input
Entering Chinese characters (e.g. `add-income a/200 c/Salary d/2025-10-01 des/午餐`) flows into the parser and storage logic, which either crashes in downstream code or produces inconsistent behaviour because the codebase was written assuming ASCII-only text.

### LINKED ISSUE #192: [PE-D][Tester D] Adding non-ASCII characters causes an unreadable description
The application does not correctly handle non-ASCII characters (e.g., Arabic, Chinese, accented characters) in the `des/` description field. When a user provides a description containing such characters, the input is accepted, but the data is corrupted during processing or rendering.

This results in the description being displayed as a series of question marks (e.g., "???") when the user runs `list-expense` or `list-income`. This bug makes the description feature unusable for any language that does not use the basic ASCII character set.

Steps to reproduce
1. Add an income or expense with non-ASCII characters in the description: `add-income a/200 c/Salary d/2025-10-01 des/هل هذا يعمل؟`
2. List the incomes to view: `list-income`

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by JordanTwz**
Closes #173.
Closes #192.

### CODE REVIEW

File: src/test/java/seedu/fintrack/FinTrackTest.java [hunk 1]
```diff
@@ -112,6 +114,17 @@ void invalidCommand_thenExit() throws Exception {
...
+    void nonAsciiInput_rejectedWithError() throws Exception {
+        String script = String.join("\n",
+                "add-income a/200 c/Salary d/2025-10-01 des/\u5348\u9910",
+                "bye");
+        String s = run(script);
+        mustContain(s, "Error: Unsupported characters detected. Please use standard ASCII text only.");
+        mustNotContain(s, "Income added:");
+        mustContain(s, "Bye. Hope to see you again soon!");
+    }
+
```
Comment (noellethen) [inline src/test/java/seedu/fintrack/FinTrackTest.java]: I like that you included unit tests for this feature as well!
