### PR TITLE
Fix CSV summary omission, preserve des/ descriptions, prevent NaN summaries

### LINKED ISSUE #132: Bugs Discovered in FinTrack
# Bugs Discovered in FinTrack

### 1. CSV summary silently omitted
- **Severity:** High  
- **Location:** `src/main/java/seedu/fintrack/storage/CsvStorage.java:41`, `CsvStorage.java:95`

**Problem**  
`CsvStorage.export` promises a summary section (totals and balance) but never calls `writeSummarySection`, so the exported CSV ends after the last transaction row.

**How to Reproduce**
1. Launch FinTrack.  
2. Enter at least one income and one expense (e.g. `add-income a/1000 c/SALARY d/2025-01-01`, `add-expense a/100 c/FOOD d/2025-01-02`).  
3. Run `export output.csv`.  
4. Open `output.csv`: the summary rows are missing even though totals/balance were passed into `export`.

**Suggested Fix**  
Invoke `writeSummarySection` after writing the transaction rows so the exported CSV matches the documented behaviour.

---

### 2. Descriptions truncated when they contain prefixes
- **Severity:** Medium  
- **Location:** `src/main/java/seedu/fintrack/Parser.java:96`, `Parser.java:122`

**Problem**  
`Parser.getValue` stops reading a value as soon as it encounters the next known prefix anywhere in the string. Descriptions that legitimately contain `a/`, `c/`, `d/`, or `des/` lose the text after that sequence.

**How to Reproduce**
1. Run `add-expense a/12.5 c/FOOD d/2025-10-01 des/Lunch with c/friends`.  
2. Inspect the printed confirmation: description becomes “Lunch with” instead of the intended “Lunch with c/friends”.

**Suggested Fix**  
Only treat a token as a new prefix when it begins at the start of the string or immediately follows whitespace, so embedded substrings aren’t misinterpreted.

---

### 3. Percentage summaries can show `NaN%`
- **Severity:** Medium  
- **Location:** `src/main/java/seedu/fintrack/Ui.java:509`, `Ui.java:569`

**Problem**  
`printExpenseByCategory` and `printIncomeByCategory` divide by the total amount without guarding against zero. If all entries in the chosen dataset sum to zero, the user sees `NaN%` for every percentage.

**How to Reproduce**
1. Add an income with zero amount: `add-income a/0 c/GIFT d/2025-10-01`.  
2. Run `summary-income`.  
3. Output shows `NaN%` for the category breakdown.

**Suggested Fix**  
Skip percentage printing (or show 0 %) when `totalExpense`/`totalIncome` is zero to keep the summary readable.

### PR DESCRIPTION
**Pull request by JordanTwz**
- Call `writeSummarySection` during CSV export so totals and balance appear correctly.  

- Allow `des/` descriptions to take the rest of the command and refine prefix detection.  

- Guard zero totals in summary printers to show friendly text instead of `NaN%`.  

- Add automated tests for the above fixes. 

Closes #132 and #98.

### CODE REVIEW

File: src/test/java/seedu/fintrack/ParserTest.java [hunk 1]
```diff
@@ -132,6 +132,27 @@ public void parseAddExpense_valid_withDescription() {
...
+     * Ensures descriptions with embedded spaces and prefix-like substrings remain intact.
+     */
+    @Test
+    public void parseAddExpense_descriptionContainsPrefixWithSpaces_textPreserved() {
+        String input = addExpense("12.50", "food", "2025-10-01",
+                "Lunch with c/      friends");
+        Expense e = Parser.parseAddExpense(input);
+        assertEquals("Lunch with c/      friends", e.getDescription());
+    }
+
```
Comment (goodguyryan) [inline src/test/java/seedu/fintrack/ParserTest.java]: Thank you for updating the tests!
